---
  - name: Using Loops
    hosts: dbserver
    tasks:
      - name: Install software
        apt:
          name: "{{item.a}}"
          state: "{{item.b}}"
          update_cache: "{{item.c}}"
        with_items:
          - {a: tomcat8,b: present,c: no}
          - {a: git,b: absent,c: no}
          - {a: apache2,b: absent,c: no}
          - {a: tree,b: present,c: yes}
...