---
  - name: Using Host Scope Variable
    hosts: webserver
    tasks:
      - name : User creation
        user:
          name: "{{a}}"
          password: "{{b}}"
          home: "{{c}}"
          uid: "{{d}}"
          shell: "{{e}}"
...          