    - name: Installing apache2
        apt:
          name: apache2
          state: present
      - name: Edit index.html file
        copy:
          content: "Welcome to Playbook"
          dest: /var/www/html/index.html
      - name: restarting apache2
        service:
          service: apache2
          state: restarted
...